# Probabilistic Matrix Factorization 
## Introduction
In this notebook, we implement probabilistic matrix factorization (PMF) on movie rating dataset.

Matrix factorization is a method to decompose a matrix into multiplication of matrices (usually two matrices). A matrix can represent a dyadic data. Matrix factorization is a way to better understand the components (dyads), and use them in further tasks. The goal is to find those unknown matrices.

Probabilistic matrix factorization (PMF) is a probabilistic extension of matrix factorization where unknown parameters are described with their probability distributions. Similar to matrix factorization, the goal of PMF is to learn embeddings from dyadic/relational data (each matrix entry is a dyad, e.g., user-item rating, document-word count, user-user link). If the matrix has missing values, by learning decomposition based on observed entries, missing values can be pre dicted. This technique is useful in variety of applications such as recommender systems/collaborative filtering, link prediction in social network, and so on. In this project, are going to use PMF in collaborating filtering. The goal of collab orative filtering is to infer user preferences for items given a large but incomplete collection of preferences for many users. If we let each row of the original matrix represent a user, and each column represent a product, we can interpret the entries of the matrix to be the rating given to a product by a user.

By learning latent features for users and movies using the seen ratings, we are able to predict the ratings for the unseen entries. 

### Model 
For more clarification, we show the model in the context of movie ratings. Let $R$ be the matrix of ratings which is partially (and sparsely) filled by users' ratings for movies. Let us assume that there are $N$ users and $M$ movies in total. The goal is to find a decomposition for $R$ such that:
$$R \approx U^T V$$
where $U$ is a $d\times N$ matrix describing users and $V$ is a $d\times M$ matrix describing movies. 

Figure below shows an illustration of this model where each column of $U$ and $V$ learn a representation for the users and movies respectively.

<img src="matrix_fact.png",style="max-width:100%; width: 50%">


Given feature vectors for $U_i$ user and $V_j$, the distribution of the corresponding rating is:

$$R(i,j) \sim N(U_i^TV_j , \sigma^2)$$
$$U_i \sim N(0, \sigma_u^2 I) ~~~~ V_j \sim N(0, \sigma_v^2 I)$$

The graphical model of it is:

<img src="graph-model.png",height: 20>

Our objective is to find $U$ and $V$ such that they have the maximum probabillity to generate seen ratings $R$. This method is called Maximum a Posteriori (MAP) estimation. Note that $\lambda$ is a tuning parameter resulting in more stability. Let $D$ represent set of all observed data such that: $D~: ~\{(i,j) ~| ~R(i,j)~is ~given\}$. Then the objective is:

$$\underset{U,V}{\max} ~ \log p(U,V|R) $$
$$\underset{U,V}{\max} ~ L(U,V)=-\frac{1}{2\sigma^2} \sum_{(i,j)\in D} {(R_{ij} - U_i^{\intercal} V_j)}^2 - \frac{\lambda}{2} \sum_{i=1}^{M} {||U_i||}^2 - \frac{\lambda}{2} \sum_{j=1}^{N} {||V_j||}^2$$

The optimization algorithm is as follows:

- Initialize $U^{(0)}$ and $V^{(0)}$
- For $t = 1:T$
    - $U^{(t)}_i = {\left[ \lambda I + \sum_{j:(i,j)\in D} \frac{1}{\sigma^2} {V^{(t-1)}_j}^{\intercal}V^{(t-1)}_j  \right]}^{-1} \left(\sum_{j:(i,j)\in D} \frac{1}{\sigma^2}R_{ij} ~ V^{(t-1)}_j \right)$
    - $V^{(t)}_j = {\left[ \lambda I + \sum_{i:(i,j)\in D} \frac{1}{\sigma^2} {U^{(t)}_i}^{\intercal} U^{(t)}_i  \right]}^{-1} \left(\sum_{i:(i,j)\in D} \frac{1}{\sigma^2}R_{ij} ~ U^{(t)}_i \right)	
$

    - End for.
    
    
Now, the first step is to import the data.    


You need to load your data, and put it in a matrix called $R$. Make sure to convert the ratings into floats - not categorical variables. The goal for you is to complete the matrix and find the missing entries. To make calculations easier, create a new matrix with 3 columns. Put the row indices (user ids) in the first row, and column indices (movie ids) in second column, and let the third column show the ratings.
Here is an implementation of it for MovieLens dataset.

In [30]:
## Load your data here...
# example with MovieLens data:
import numpy as np
import random
import pandas as pd
prefer = []
o = open('data/u.data.txt', 'r')
for line in o.readlines():  
    (userid, movieid, rating, ts) = line.split('\t')  
    uid = int(userid)
    mid = int(movieid)
    rat = float(rating)
    prefer.append([uid, mid, rat])
    #data = array(prefer)
    
o.close()
#print(line)
#print(prefer[-5:])

In [31]:
data = array(prefer)
N = len(unique(data[:,0])) # number of users
M = len(unique(data[:,1])) # number of movies
print("In this dataset, there are {} users and {} movies\objects.".format(N,M))

In this dataset, there are 943 users and 1682 movies\objects.


In [142]:
print("there are {} given ratings total.".format(len(data)))
      
print("Here is the first 10 rows in my processesed data")
data[:10]

there are 100000 given ratings total.
Here is the first 10 rows in my processesed data


array([[196., 242.,   3.],
       [186., 302.,   3.],
       [ 22., 377.,   1.],
       [244.,  51.,   2.],
       [166., 346.,   1.],
       [298., 474.,   4.],
       [115., 265.,   2.],
       [253., 465.,   5.],
       [305., 451.,   3.],
       [  6.,  86.,   3.]])

Now you need to run your algorithm. Note that at each sep, you need to update all of the movies' features as well as all of the users' features. You can set lambda = 0.1, and variances to be 1. Note that these parameter choices are up to you, and feel free to tune them the way you want. You can set the number of iterations to be 100.

In [74]:
## Initialize U and V randomly. Note that U should be d by N and V should be d by M.
d = 5
lam = 0.1
U = np.random.normal(size=(d,N))
V = np.random.normal(size=(d,M))
print(U)
# np.random.multivariate_normal

[[ 0.59540839  0.56073779 -1.28719171 ... -0.20603952 -1.06280355
  -1.19800203]
 [-1.23444186 -0.4839017  -0.51358529 ... -1.21529391 -0.07156841
  -1.2568771 ]
 [ 0.5449474   0.08393271 -2.18265959 ... -0.67143175  0.80125847
  -0.59245604]
 [ 1.46276228  0.35933278  0.36978873 ...  1.43202382  0.73647167
  -0.81903272]
 [-1.95092272 -0.62433419  0.06094896 ...  1.44434963 -2.1466248
   0.08251723]]


To make the calculations easier, you should keep track of some values at each step. Note that to update vector for a user, you need to have access to all the movies rated by that user (the same for the movies; to update vector for a movie, you need the id of all of the users that have rated that movie.)
Since these don't change, we suggest you to construct a dictionary for each user as key, and id of movies rated by that user to be the values (as a list). You should do the same for movies.
These are only some suggestions, feel free to use any method that you like. :)

In [121]:
###### you can construct two dictionaries one for the user and one for the movies here.
## hint: you can use defaultdict

from collections import defaultdict
#
u_dict = defaultdict(list)
for i, j in zip(data[:,0],zip(data[:,1],data[:,2])):
    u_dict[i].append(j)
    
m_dict = defaultdict(list)
for i, j in zip(data[:,1],zip(data[:,0],data[:,2])):
    m_dict[i].append(j)

print(u_list[196])
print(m_list[393])

[(242.0, 3.0), (393.0, 4.0), (381.0, 4.0), (251.0, 3.0), (655.0, 5.0), (67.0, 5.0), (306.0, 4.0), (238.0, 4.0), (663.0, 5.0), (111.0, 4.0), (580.0, 2.0), (25.0, 4.0), (286.0, 5.0), (94.0, 3.0), (692.0, 5.0), (8.0, 5.0), (428.0, 4.0), (1118.0, 4.0), (70.0, 3.0), (66.0, 3.0), (257.0, 2.0), (108.0, 4.0), (202.0, 3.0), (340.0, 3.0), (287.0, 3.0), (116.0, 3.0), (382.0, 4.0), (285.0, 5.0), (1241.0, 3.0), (1007.0, 4.0), (411.0, 4.0), (153.0, 5.0), (13.0, 2.0), (762.0, 3.0), (173.0, 2.0), (1022.0, 4.0), (845.0, 4.0), (269.0, 3.0), (110.0, 1.0)]
[(196.0, 4.0), (303.0, 4.0), (290.0, 3.0), (145.0, 5.0), (279.0, 1.0), (307.0, 3.0), (193.0, 4.0), (94.0, 3.0), (230.0, 3.0), (87.0, 4.0), (174.0, 4.0), (38.0, 5.0), (308.0, 4.0), (43.0, 4.0), (151.0, 2.0), (109.0, 4.0), (22.0, 4.0), (92.0, 3.0), (18.0, 3.0), (7.0, 4.0), (130.0, 5.0), (387.0, 2.0), (144.0, 4.0), (5.0, 2.0), (102.0, 3.0), (330.0, 4.0), (267.0, 3.0), (95.0, 5.0), (262.0, 2.0), (200.0, 4.0), (398.0, 5.0), (299.0, 2.0), (286.0, 4.0), (405.0

Again, to update feature vector of a user, you need to compute ${V^{(t-1)}_j}^{\intercal}V^{(t-1)}_j$. We suggest you to ceate an array for all of the movies, and update these values at the end of each iteration. That way, you just need to look up the dictionary for the movie ids that a user has rated, and use those indices of your constructed vector.
You need to do the same for the movies.

In [66]:
## Constructing arrays that will make your life easier in the implementation of the algorithm ....
#print(V[:,:4])
#print(V[:,1])

def outer_col_list(inp_array,col=1):
    """returns a list of outer products of cols with themselves
    
    """
    outer_list = []
    for i in arange(inp_array.shape[col]):
        _v = array(inp_array[:,i])
        outer_list.append(np.outer(_v.T,_v))
    return outer_list

#vtv = outer_col_list(V)
#utu = outer_col_list(U)
#print(utu[:1])



[array([[ 3.12917166, -0.51676987,  0.63660511, -0.46919868,  2.55910722],
       [-0.51676987,  0.08534242, -0.10513272,  0.07748624, -0.42262606],
       [ 0.63660511, -0.10513272,  0.12951225, -0.09545474,  0.52063003],
       [-0.46919868,  0.07748624, -0.09545474,  0.07035325, -0.38372127],
       [ 2.55910722, -0.42262606,  0.52063003, -0.38372127,  2.09289565]])]


In [150]:
from numpy.linalg import inv
## Implementation of the algorithm ...

# make my dxd identity matrix
reg = lam*np.identity(5)
#print(reg)

def mykernel(reg,j_dict,matrix_list,matrix):
    update = zeros(matrix.shape)
    #print(matrix.shape)
    for key,val in j_dict.items():
        matrix_sum = zeros(matrix_list[0].shape)
        vector_sum = zeros(matrix.shape[0])
        for i in val:
            matrix_sum = matrix_sum + matrix_list[int(i[0])-1]
            vector_sum = vector_sum + i[1]*matrix[:,int(i[0]-1)]
        update[:,int(key)-1] = dot(inv(reg + matrix_sum),vector_sum)        
#            print(int(i[0]),len(matrix_list))

    return array(update)


v = V.copy()
vtv = outer_col_list(v)
for i in arange(20):
    u = mykernel(reg,dict(m_dict),vtv,v)
    utu = outer_col_list(u)
    print(u.shape,len(utu),utu[0].shape)
    v = mykernel(reg,dict(u_dict),utu,u)
    vtv = outer_col_list(v)
#    print(v.shape,vtv.shape)
    


(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)
(5, 1682) 1682 (5, 5)


In [152]:
print(data[:3])
print(np.inner(u[:,195].T,v[:,241]))
print(np.inner(u[:,185].T,v[:,301]))
print(np.inner(u[:,21].T,v[:,376]))

[[196. 242.   3.]
 [186. 302.   3.]
 [ 22. 377.   1.]]
4.626951169160195
3.278262899764008
4.862928703224339


Now that you found the optimal U and V matrices, you can predict for the missing ratings for users. For example, show 10 movies with the highest predicted ratings for 5 of the users of your choice.


In [28]:
## e.g.: If you were a movie recommending system, what would you recommend to user number 19 to watch that hasn't watched before?

### Reference:
1- Mnih, A., & Salakhutdinov, R. (2007). Probabilistic matrix factorization. In Advances in neural information processing systems (pp. 1257-1264). https://papers.nips.cc/paper/3208-probabilistic-matrix-factorization.pdf
