In [12]:
import numpy as np

x=[1,1,1]
y=[2,2,2]

z=np.concatenate([x,y])

z[0]=10

print(x)
print(y)
print(z)

[1, 1, 1]
[2, 2, 2]
[10  1  1  2  2  2]


In [14]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])