In [12]:
import numpy as np

x=[1,1,1]
y=[2,2,2]

z=np.concatenate([x,y])

z[0]=10

print(x)
print(y)
print(z)

[1, 1, 1]
[2, 2, 2]
[10  1  1  2  2  2]


In [14]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [1]:
import plotly.plotly as py
from plotly.graph_objs import *

trace0 = Scatter(
    x=[1, 2, 3, 4],
    y=[10, 15, 13, 17]
)
trace1 = Scatter(
    x=[1, 2, 3, 4],
    y=[16, 5, 11, 9]
)
data = Data([trace0, trace1])

py.plot(data, filename = 'basic-line')

u'https://plot.ly/~tz33cu/46'